name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2.2.3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1